import type { MenuItem, Restaurant, Staff } from '../types';
import { RESTAURANT_ID } from '../lib/constants';

export const demoRestaurant: Restaurant = {
  id: RESTAURANT_ID,
  name: 'ChopChop Kasi Grill',
  slug: 'chopchop-kasi-grill',
  created_at: '2026-01-05T08:00:00.000Z',
};

export const demoStaff: Staff[] = [
  {
    id: 'staff-owner',
    restaurant_id: RESTAURANT_ID,
    full_name: 'Thabo Mokoena',
    role: 'owner',
    created_at: '2026-01-05T08:00:00.000Z',
  },
  {
    id: 'staff-cashier',
    restaurant_id: RESTAURANT_ID,
    full_name: 'Naledi Dlamini',
    role: 'cashier',
    created_at: '2026-01-05T08:00:00.000Z',
  },
  {
    id: 'staff-kitchen',
    restaurant_id: RESTAURANT_ID,
    full_name: 'Sipho Khumalo',
    role: 'kitchen',
    created_at: '2026-01-05T08:00:00.000Z',
  },
];

// Keyword-based food photos (stable per item via ?lock=). If a photo fails to load or the
// device is offline, the UI falls back to the item's emoji tile — see <FoodImage/>.
const photo = (keyword: string, lock: number): string =>
  `https://loremflickr.com/400/300/${keyword}?lock=${lock}`;

// ~15 items across 4 categories, incl. 3 combos with options (brief §4).
export const demoMenu: MenuItem[] = [
  // ---- Burgers ----
  {
    id: 'm-burger-classic',
    restaurant_id: RESTAURANT_ID,
    name: 'Classic Beef Burger',
    description: 'Flame-grilled beef patty, lettuce, tomato, house sauce',
    price: 49.9,
    category: 'Burgers',
    is_combo: false,
    is_available: true,
    sort_order: 1,
    image_url: photo('burger', 11),
    emoji: '🍔',
    combo_options: [],
  },
  {
    id: 'm-burger-cheese',
    restaurant_id: RESTAURANT_ID,
    name: 'Double Cheese Burger',
    description: 'Two patties, double cheddar, pickles',
    price: 72.5,
    category: 'Burgers',
    is_combo: false,
    is_available: true,
    sort_order: 2,
    image_url: photo('cheeseburger', 12),
    emoji: '🍔',
    combo_options: [],
  },
  {
    id: 'm-burger-combo',
    restaurant_id: RESTAURANT_ID,
    name: 'Burger Combo',
    description: 'Beef burger + side + drink',
    price: 79.9,
    category: 'Burgers',
    is_combo: true,
    is_available: true,
    sort_order: 3,
    image_url: photo('burger,meal', 13),
    emoji: '🍔',
    combo_options: [
      { id: 'co-bc-side-1', menu_item_id: 'm-burger-combo', option_name: 'Choose your side', choice_label: 'Chips', price_delta: 0 },
      { id: 'co-bc-side-2', menu_item_id: 'm-burger-combo', option_name: 'Choose your side', choice_label: 'Onion Rings', price_delta: 8 },
      { id: 'co-bc-side-3', menu_item_id: 'm-burger-combo', option_name: 'Choose your side', choice_label: 'Side Salad', price_delta: 5 },
      { id: 'co-bc-drink-1', menu_item_id: 'm-burger-combo', option_name: 'Choose your drink', choice_label: 'Coke', price_delta: 0 },
      { id: 'co-bc-drink-2', menu_item_id: 'm-burger-combo', option_name: 'Choose your drink', choice_label: 'Fanta', price_delta: 0 },
      { id: 'co-bc-drink-3', menu_item_id: 'm-burger-combo', option_name: 'Choose your drink', choice_label: 'Still Water', price_delta: 0 },
    ],
  },
  {
    id: 'm-burger-chicken',
    restaurant_id: RESTAURANT_ID,
    name: 'Crispy Chicken Burger',
    description: 'Buttermilk-fried chicken fillet, slaw, mayo',
    price: 55.0,
    category: 'Burgers',
    is_combo: false,
    is_available: true,
    sort_order: 4,
    image_url: photo('chicken,burger', 14),
    emoji: '🍔',
    combo_options: [],
  },
  // ---- Chicken ----
  {
    id: 'm-chicken-2pc',
    restaurant_id: RESTAURANT_ID,
    name: '2pc Fried Chicken',
    description: 'Two pieces, secret-spice crumb',
    price: 45.0,
    category: 'Chicken',
    is_combo: false,
    is_available: true,
    sort_order: 5,
    image_url: photo('fried,chicken', 21),
    emoji: '🍗',
    combo_options: [],
  },
  {
    id: 'm-chicken-wings',
    restaurant_id: RESTAURANT_ID,
    name: 'Hot Wings (6)',
    description: 'Six saucy wings',
    price: 52.0,
    category: 'Chicken',
    is_combo: false,
    is_available: true,
    sort_order: 6,
    image_url: photo('chicken,wings', 22),
    emoji: '🍗',
    combo_options: [],
  },
  {
    id: 'm-chicken-combo',
    restaurant_id: RESTAURANT_ID,
    name: 'Chicken Feast Combo',
    description: '3pc chicken + side + drink',
    price: 89.9,
    category: 'Chicken',
    is_combo: true,
    is_available: true,
    sort_order: 7,
    image_url: photo('fried,chicken,meal', 23),
    emoji: '🍗',
    combo_options: [
      { id: 'co-cc-side-1', menu_item_id: 'm-chicken-combo', option_name: 'Choose your side', choice_label: 'Chips', price_delta: 0 },
      { id: 'co-cc-side-2', menu_item_id: 'm-chicken-combo', option_name: 'Choose your side', choice_label: 'Pap & Gravy', price_delta: 6 },
      { id: 'co-cc-side-3', menu_item_id: 'm-chicken-combo', option_name: 'Choose your side', choice_label: 'Coleslaw', price_delta: 4 },
      { id: 'co-cc-drink-1', menu_item_id: 'm-chicken-combo', option_name: 'Choose your drink', choice_label: 'Coke', price_delta: 0 },
      { id: 'co-cc-drink-2', menu_item_id: 'm-chicken-combo', option_name: 'Choose your drink', choice_label: 'Sprite', price_delta: 0 },
      { id: 'co-cc-drink-3', menu_item_id: 'm-chicken-combo', option_name: 'Choose your drink', choice_label: 'Fuze Iced Tea', price_delta: 3 },
    ],
  },
  {
    id: 'm-chicken-strips',
    restaurant_id: RESTAURANT_ID,
    name: 'Chicken Strips (5)',
    description: 'Five crispy tenders + dip',
    price: 58.0,
    category: 'Chicken',
    is_combo: false,
    is_available: true,
    sort_order: 8,
    image_url: photo('chicken,tenders', 24),
    emoji: '🍗',
    combo_options: [],
  },
  // ---- Sides ----
  {
    id: 'm-side-chips-s',
    restaurant_id: RESTAURANT_ID,
    name: 'Chips (Small)',
    description: 'Golden hand-cut chips',
    price: 22.0,
    category: 'Sides',
    is_combo: false,
    is_available: true,
    sort_order: 9,
    image_url: photo('fries', 31),
    emoji: '🍟',
    combo_options: [],
  },
  {
    id: 'm-side-chips-l',
    restaurant_id: RESTAURANT_ID,
    name: 'Chips (Large)',
    description: 'Sharing portion',
    price: 34.0,
    category: 'Sides',
    is_combo: false,
    is_available: true,
    sort_order: 10,
    image_url: photo('french,fries', 32),
    emoji: '🍟',
    combo_options: [],
  },
  {
    id: 'm-side-onionrings',
    restaurant_id: RESTAURANT_ID,
    name: 'Onion Rings',
    description: 'Six battered rings',
    price: 28.0,
    category: 'Sides',
    is_combo: false,
    is_available: true,
    sort_order: 11,
    image_url: photo('onion,rings', 33),
    emoji: '🧅',
    combo_options: [],
  },
  {
    id: 'm-side-salad',
    restaurant_id: RESTAURANT_ID,
    name: 'Side Salad',
    description: 'Fresh garden salad',
    price: 26.0,
    category: 'Sides',
    is_combo: false,
    is_available: false, // demonstrates the "unavailable" state on the Till
    sort_order: 12,
    image_url: photo('salad', 34),
    emoji: '🥗',
    combo_options: [],
  },
  // ---- Drinks ----
  {
    id: 'm-drink-coke',
    restaurant_id: RESTAURANT_ID,
    name: 'Coke 330ml',
    description: null,
    price: 18.0,
    category: 'Drinks',
    is_combo: false,
    is_available: true,
    sort_order: 13,
    image_url: photo('cola,can', 41),
    emoji: '🥤',
    combo_options: [],
  },
  {
    id: 'm-drink-fanta',
    restaurant_id: RESTAURANT_ID,
    name: 'Fanta 330ml',
    description: null,
    price: 18.0,
    category: 'Drinks',
    is_combo: false,
    is_available: true,
    sort_order: 14,
    image_url: photo('orange,soda', 42),
    emoji: '🥤',
    combo_options: [],
  },
  {
    id: 'm-drink-water',
    restaurant_id: RESTAURANT_ID,
    name: 'Still Water 500ml',
    description: null,
    price: 14.0,
    category: 'Drinks',
    is_combo: false,
    is_available: true,
    sort_order: 15,
    image_url: photo('water,bottle', 43),
    emoji: '💧',
    combo_options: [],
  },
];
